services:
  - type: web
    name: denki2-cbt
    runtime: python
    buildCommand: pip install -r server/requirements.txt
    startCommand: gunicorn --chdir server --config server/gunicorn.conf.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
